phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - $(aws ecrbget-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=161452358598.dkr.ecr.us-west-2.amazonaws.com/tweetapp-registery-1
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image
      - docker-compose up -d
      - docker tag REPOSITORY_URI:latest $ REPOSITORY_URI"$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing images definitions file...
      - printf '[{"name":"mongo-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
  artifacts:
    files:
     - imagedefinitions.json
