version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION
      - REPOSITORY_URI=161452358598.dkr.ecr.us-west-2.amazonaws.com/tweetapp-registery-1
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image
      - docker pull mongo:4.2
      - docker tag mongo:4.2 161452358598.dkr.ecr.us-west-2.amazonaws.com/tweetapp-registery-1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker images
      - docker push 161452358598.dkr.ecr.us-west-2.amazonaws.com/tweetapp-registery-1
      - echo Writing images definitions file...
      - printf '[{"name":"mongo-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
